last_name = input(">> Фамилия: ")
first_name = input(">> Имя: ")
group = input(">> Группа: ")
city = input(">> Город: ")
age = int(input(">> Возраст (1-120 полных лет): "))
subject = input(">> Любимый предмет: ")
hours = float(input(">> Часов подготовки в неделю: "))

print("=" * 40)
print(" " * 20 + "КАРТОЧКА СТУДЕНТА")
print("=" * 40)
print(f"Полное имя: {first_name} {last_name}")
print(f"Группа: {group}")
print(f"Город: {city}")
print(f"Возраст: {age}")
print(f"Возраст через 4 года: {age + 4}")
print(f"Любимый предмет: {subject}")
print(f"Часов за 1 неделю: {hours:.2f}")
print(f"Часов за 4 недели: {hours * 4:.2f}")
print(f"Часов в день (среднее): {hours / 7:.2f}")
print("=" * 40)
